# Generated by Django 4.2.3 on 2023-07-15 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.CharField(default='random@gmail.com', max_length=250, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('pollingUnit_uniqueid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedLgaResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField(max_length=11)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedStateResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField(max_length=11)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncedWardResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=50)),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField(max_length=11)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_id', models.IntegerField(max_length=11)),
                ('lga_name', models.CharField(max_length=50)),
                ('lga_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(max_length=11)),
                ('party_name', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_id', models.IntegerField(max_length=11)),
                ('ward_name', models.CharField(max_length=50)),
                ('ward_description', models.TextField()),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
                ('lga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_lga_id', to='election_info.lga')),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_unit_number', models.CharField(default='N/A', max_length=50, null=True)),
                ('polling_unit_name', models.CharField(default='N/A', max_length=50, null=True)),
                ('polling_unit_description', models.TextField()),
                ('lat', models.CharField(default='N/A', max_length=255, null=True)),
                ('long', models.CharField(default='N/A', max_length=255, null=True)),
                ('entered_by_user', models.CharField(default='N/A', max_length=50, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(default='N/A', max_length=50, null=True)),
                ('lga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_lga_id', to='election_info.lga')),
                ('polling_unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_unit_uniqueid', to='election_info.ward')),
                ('unique_ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_state_id', to='election_info.states')),
                ('ward_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_ward_id', to='election_info.ward')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lga_state_id', to='election_info.states'),
        ),
        migrations.CreateModel(
            name='AnnouncedPuResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_abbreviation', models.CharField(max_length=4)),
                ('party_score', models.IntegerField(max_length=11)),
                ('entered_by_user', models.CharField(max_length=50)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.CharField(max_length=50)),
                ('polling_unit_uniqueid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_unit_uniqid', to='election_info.pollingunit')),
            ],
        ),
    ]
