# Generated by Django 4.2.3 on 2023-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_info', '0003_announced_lga_results_user_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_description',
            field=models.TextField(null=True),
        ),
    ]
