# Generated by Django 4.2.3 on 2023-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_info', '0004_alter_polling_unit_polling_unit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling_unit',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
