# Generated by Django 4.2.3 on 2023-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_info', '0005_alter_polling_unit_date_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='pollingunit_uniqueid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_lga_results',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_pu_results',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_state_results',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announced_ward_results',
            name='party_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.IntegerField(),
        ),
    ]
